// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardHoverController from "./card_hover_controller"
application.register("card-hover", CardHoverController)

import HamburgerController from "./hamburger_controller"
application.register("hamburger", HamburgerController)

import PreviewsController from "./previews_controller"
application.register("previews", PreviewsController)
